# Generated by Django 6.0.7 on 2026-07-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.PositiveIntegerField()),
                ('version', models.CharField(max_length=10)),
                ('account_id', models.CharField(db_index=True, max_length=50)),
                ('instance_id', models.CharField(db_index=True, max_length=50)),
                ('srcaddr', models.GenericIPAddressField(db_index=True)),
                ('dstaddr', models.GenericIPAddressField(db_index=True)),
                ('srcport', models.PositiveIntegerField()),
                ('dstport', models.PositiveIntegerField()),
                ('protocol', models.PositiveIntegerField()),
                ('packets', models.BigIntegerField()),
                ('bytes', models.BigIntegerField()),
                ('starttime', models.BigIntegerField(db_index=True)),
                ('endtime', models.BigIntegerField(db_index=True)),
                ('action', models.CharField(db_index=True, max_length=20)),
                ('log_status', models.CharField(db_index=True, max_length=20)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.uploadedfile')),
            ],
        ),
    ]
