# Generated by Django 6.0.7 on 2026-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
