# Generated by Django 6.0.7 on 2026-07-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='account_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='dstaddr',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='instance_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='log_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='srcaddr',
            field=models.GenericIPAddressField(),
        ),
    ]
