services:
  backend:
    build:
      context: ./backend
    container_name: aceable-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: aceable-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000/api/
    volumes:
      - ./frontend:/app
      - /app/node_modules
